name: CI

on:
  push:
    branches: 
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v1
    - name: Check dir
      run: ls -la
    - name: End!
      run: echo "Finish"
